### ISSUE TITLE
Do not add entries from non-default branches

### ISSUE THREAD

**Issue by ddgenome** [atomist-skills/keep-a-changelog-skill#100]
I pushed this commit: https://github.com/atomist-skills/helloworld-skill/commit/7082cbcb30c5e30edd81f272646ba39cbe8a879a and even though it was not on the default branch, this skill added an entry to the changelog.

https://github.com/atomist-skills/helloworld-skill/commit/461ea15f42199b5a8cc08bc306ce29cfd091e992

Further, when I created the pull request, https://github.com/atomist-skills/helloworld-skill/pull/64 , and added the changelog:fixed label to it, this skill added an entry for the pull request, even though it has not been merged.

https://github.com/atomist-skills/helloworld-skill/commit/848f2737172a2cfeb91bec1d4247c8d058da92b2

**Comment by cdupuis** [comment]
The first part of that issue is indeed something we should change; but that has never been implemented. Therefore adding removing the bug label.

The PR was raised by an outdated version of this skill from staging. This has already been fixed.

**Comment by cdupuis** [comment]
I misspoke:

```
if (push.branch !== push.repo.defaultBranch) {
	return status.success("Ignoring pushes to non-default branch").hidden();
}
```

So the changeling entry for the commit must have been from staging as well.
